In [1]:
import numpy as np

image = np.array([
    [10, 20],
    [20, 34],
])

print(image)

[[10 20]
 [20 34]]


In [2]:
vector = image.reshape(-1)

print(vector)

[10 20 20 34]


In [3]:
img1 = np.array([12, 34, 53, 64])
img2 = np.array([13, 20, 40, 63])

diff = img1 - img2

print(diff)

[-1 14 13  1]


In [4]:
abs_diff = np.abs(diff)

print(abs_diff)

[ 1 14 13  1]


In [5]:
l1 = np.sum(abs_diff)

print(l1)

29


In [6]:
for a,b in zip(img1,img2):
    print(
        a,
        b,
        abs(a-b)
    )

12 13 1
34 20 14
53 40 13
64 63 1


In [7]:
def l1_distance(img1, img2):
  diff = img1 - img2
  return np.sum(np.abs(diff))

In [8]:
print(l1_distance(img1, img2))

29


In [9]:
def l2_distance(img1, img2):
  diff = img1 - img2
  return np.sqrt(np.sum(np.square(diff)))

In [10]:
print(l2_distance(img1, img2))

19.157244060668017


In [11]:
X_train = np.array([
    [1, 1],
    [2, 2],
    [3, 3]
])

y_train = np.array([
    "cat",
    "dog",
    "mug"
])

In [12]:
X_test = np.array([2,2])

In [13]:
for img in X_train:
  print(l1_distance(img, X_test))

2
0
2


In [14]:
nearest = np.argmin([l1_distance(img, X_test) for img in X_train])

print(y_train[nearest])

dog


In [15]:
import numpy as np


class NearestNeighbor(object):

    def __init__(self):
        """
        Constructor.

        This runs when:
            nn = NearestNeighbor()

        At this point the model knows nothing.
        """
        pass


    def train(self, X, y):
        """
        X : Training images
            Shape = (N, D)

        y : Labels
            Shape = (N,)

        N = number of training examples
        D = number of features/pixels

        Example:
            X.shape = (50000, 3072)
            y.shape = (50000,)
        """

        # Simply memorize training data
        self.Xtr = X
        self.ytr = y


    def predict(self, X):
        """
        Predict labels for test data.

        X:
            Shape = (num_test, D)

        Returns:
            Ypred
        """

        num_test = X.shape[0]

        Ypred = np.zeros(
            num_test,
            dtype=self.ytr.dtype
        )

        # Loop through every test image
        for i in range(num_test):

            # Compute L1 distance between
            # current test image and ALL training images
            distances = np.sum(
                np.abs(
                    self.Xtr - X[i, :]
                ),
                axis=1
            )

            # Find smallest distance
            min_index = np.argmin(
                distances
            )

            # Copy label of nearest image
            Ypred[i] = self.ytr[
                min_index
            ]

        return Ypred

In [16]:
import numpy as np
X = np.array([
    [2, 2],
    [8, 8]
])

In [17]:
print(X.shape[0])

2
